/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List todos with filters and pagination */
        get: operations["TodosController_findAll"];
        put?: never;
        /** Create a todo */
        post: operations["TodosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one todo by id */
        get: operations["TodosController_findOne"];
        put?: never;
        post?: never;
        /** Delete a todo */
        delete: operations["TodosController_remove"];
        options?: never;
        head?: never;
        /** Update a todo partially */
        patch: operations["TodosController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Priority: "low" | "medium" | "high";
        TodoEntity: {
            /**
             * Format: uuid
             * @example 1dd3c2b5-5fc4-4e7b-b3b1-6f91f0ef5e61
             */
            id: string;
            /** @example Prepare the project demo */
            title: string;
            /** @example false */
            completed: boolean;
            /** @example medium */
            priority: components["schemas"]["Priority"];
            /**
             * Format: date
             * @example 2026-09-19
             */
            dueDate: string | null;
            /**
             * Format: date-time
             * @example 2026-09-19T08:30:00.000Z
             */
            createdAt: string;
        };
        TodoListMetaEntity: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        TodoListResponseEntity: {
            items: components["schemas"]["TodoEntity"][];
            meta: components["schemas"]["TodoListMetaEntity"];
        };
        CreateTodoDto: {
            /** @example Prepare the project demo */
            title: string;
            /** @description Defaults to false when omitted */
            completed?: boolean;
            /** @description Defaults to medium when omitted */
            priority?: components["schemas"]["Priority"];
            /**
             * Format: date
             * @example 2026-09-19
             */
            dueDate?: string | null;
        };
        UpdateTodoDto: {
            /** @example Prepare the project demo */
            title?: string;
            /** @description Defaults to false when omitted */
            completed?: boolean;
            /** @description Defaults to medium when omitted */
            priority?: components["schemas"]["Priority"];
            /**
             * Format: date
             * @example 2026-09-19
             */
            dueDate?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TodosController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                dueDate?: string;
                priority?: "low" | "medium" | "high";
                /** @description When true, selects high priority todos; when false, selects low or medium priority todos. */
                urgent?: boolean;
                completed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoListResponseEntity"];
                };
            };
            /** @description Invalid filter or pagination value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TodosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoEntity"];
                };
            };
            /** @description Invalid todo data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TodosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoEntity"];
                };
            };
            /** @description Todo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TodosController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Todo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TodosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoEntity"];
                };
            };
            /** @description Invalid todo data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Todo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
